import type { Language, RiskLevel } from '@/types';

export interface LocalizedRiskText {
  reasons: Record<string, string>;
  noSignals: string;
  actions: string[];
  summary: Record<RiskLevel, string>;
  strongWarning: string;
  disclaimer: string;
  predictions: Record<string, string>;
}

const en: LocalizedRiskText = {
  reasons: {},
  noSignals: 'No strong scam signals detected, but stay alert.',
  actions: ['When in doubt, do not respond or click anything.', 'Verify the sender using an official phone number or app.', 'Ask a trusted person for a second opinion.'],
  summary: { safe:'No strong warning detected. Verify unexpected requests independently.', caution:'This content may be suspicious. Verify the sender before acting.', high:'This content shows strong scam indicators. Do not respond, click links, pay, or share information.' },
  strongWarning: 'Several dangerous warning signs appear together. Stop and verify independently before doing anything.',
  disclaimer: 'This is a risk estimate, not a guarantee.',
  predictions: { phishing:'phishing', legitimate:'legitimate' },
};

const hi: LocalizedRiskText = {
  reasons: {urgency:'जल्दी कार्रवाई करने का दबाव',account_suspension:'खाता बंद करने की धमकी',credential_request:'OTP, PIN या पासवर्ड माँगा गया',payment_request:'भुगतान या शुल्क माँगा गया',prize_giveaway:'अनचाहे इनाम या लॉटरी का दावा',impersonation:'किसी संस्था या परिचित का रूप धारण करना',suspicious_link:'संदिग्ध लिंक खोलने का दबाव',url_shortener:'लिंक का असली पता छिपाया गया',investment_scam:'अवास्तविक निवेश लाभ का वादा',delivery_scam:'नकली डिलीवरी या सीमा शुल्क संदेश',act_immediately:'तुरंत जवाब देने का दबाव',prize:'अनचाहे इनाम का दावा',investment:'अवास्तविक निवेश का वादा',credential:'संवेदनशील जानकारी माँगी गई',account:'खाता बंद करने की धमकी',gift_card:'गिफ्ट कार्ड से भुगतान माँगा गया',money_transfer:'पैसे ट्रांसफर करने को कहा गया',delivery:'नकली डिलीवरी शुल्क',tech_support:'नकली तकनीकी सहायता',government:'सरकारी संस्था की नकल',family:'नकली पारिवारिक आपातकाल',loan:'अनचाहा ऋण प्रस्ताव',free_reward:'मुफ़्त इनाम का लालच',fake_login:'नकली लॉगिन जैसा लिंक',raw_ip:'डोमेन की जगह IP पता',at_symbol:'लिंक में भ्रामक @ चिन्ह',lookalike_domain:'नकली या मिलता-जुलता डोमेन',qr_payment:'QR से भुगतान भेजने का जोखिम'},
  noSignals:'कोई मजबूत घोटाला संकेत नहीं मिला, फिर भी सावधान रहें।', actions:['जवाब न दें, लिंक न खोलें और कोई कोड साझा न करें।','आधिकारिक ऐप या नंबर से भेजने वाले की पुष्टि करें।','किसी विश्वसनीय व्यक्ति से दूसरी राय लें।'], summary:{safe:'कोई मजबूत चेतावनी नहीं मिली। अनचाहे अनुरोध की स्वतंत्र रूप से पुष्टि करें।',caution:'यह सामग्री संदिग्ध हो सकती है। कार्रवाई से पहले भेजने वाले की पुष्टि करें।',high:'इसमें मजबूत घोटाला संकेत हैं। जवाब, भुगतान या जानकारी साझा न करें।'}, strongWarning:'कई खतरनाक संकेत एक साथ मिले हैं। रुकें और स्वतंत्र रूप से पुष्टि करें।', disclaimer:'यह जोखिम का अनुमान है, गारंटी नहीं।', predictions:{phishing:'फ़िशिंग',legitimate:'वैध'},
};

const bn: LocalizedRiskText = {
  reasons:{urgency:'দ্রুত কাজ করার চাপ',account_suspension:'অ্যাকাউন্ট বন্ধ করার হুমকি',credential_request:'OTP, PIN বা পাসওয়ার্ড চাওয়া হয়েছে',payment_request:'টাকা বা ফি চাওয়া হয়েছে',prize_giveaway:'অপ্রত্যাশিত পুরস্কারের দাবি',impersonation:'সংস্থা বা পরিচিত ব্যক্তির ছদ্মবেশ',suspicious_link:'সন্দেহজনক লিংক খোলার চাপ',url_shortener:'লিংকের আসল গন্তব্য লুকানো',investment_scam:'অবাস্তব বিনিয়োগ লাভের প্রতিশ্রুতি',delivery_scam:'ভুয়া ডেলিভারি বার্তা',act_immediately:'এখনই উত্তর দেওয়ার চাপ',prize:'অপ্রত্যাশিত পুরস্কারের দাবি',investment:'অবাস্তব বিনিয়োগের প্রতিশ্রুতি',credential:'সংবেদনশীল তথ্য চাওয়া হয়েছে',account:'অ্যাকাউন্ট বন্ধের হুমকি',gift_card:'গিফট কার্ডে টাকা চাওয়া',money_transfer:'টাকা পাঠাতে বলা হয়েছে',delivery:'ভুয়া ডেলিভারি ফি',tech_support:'ভুয়া প্রযুক্তি সহায়তা',government:'সরকারি সংস্থার ছদ্মবেশ',family:'ভুয়া পারিবারিক জরুরি অবস্থা',loan:'অনাকাঙ্ক্ষিত ঋণের প্রস্তাব',free_reward:'বিনামূল্যের পুরস্কারের প্রলোভন',fake_login:'ভুয়া লগইন ধরনের লিংক',raw_ip:'ডোমেনের বদলে IP ঠিকানা',at_symbol:'লিংকে বিভ্রান্তিকর @ চিহ্ন',lookalike_domain:'নকল বা মিলযুক্ত ডোমেন',qr_payment:'QR দিয়ে টাকা পাঠানোর ঝুঁকি'},
  noSignals:'শক্তিশালী প্রতারণার লক্ষণ পাওয়া যায়নি, তবুও সতর্ক থাকুন।',actions:['উত্তর দেবেন না, লিংক খুলবেন না বা কোনো কোড দেবেন না।','অফিসিয়াল অ্যাপ বা নম্বর দিয়ে প্রেরককে যাচাই করুন।','বিশ্বস্ত কারও দ্বিতীয় মতামত নিন।'],summary:{safe:'শক্তিশালী সতর্কতা পাওয়া যায়নি। অপ্রত্যাশিত অনুরোধ আলাদাভাবে যাচাই করুন।',caution:'বিষয়টি সন্দেহজনক হতে পারে। কাজ করার আগে প্রেরককে যাচাই করুন।',high:'এতে শক্তিশালী প্রতারণার লক্ষণ আছে। উত্তর, টাকা বা তথ্য দেবেন না।'},strongWarning:'একাধিক বিপজ্জনক লক্ষণ একসঙ্গে পাওয়া গেছে। থামুন এবং আলাদাভাবে যাচাই করুন।',disclaimer:'এটি ঝুঁকির অনুমান, নিশ্চয়তা নয়।',predictions:{phishing:'ফিশিং',legitimate:'বৈধ'},
};

const ta: LocalizedRiskText = {
  reasons:{urgency:'விரைவாகச் செயல்பட அழுத்தம்',account_suspension:'கணக்கை முடக்கும் மிரட்டல்',credential_request:'OTP, PIN அல்லது கடவுச்சொல் கேட்கப்பட்டது',payment_request:'பணம் அல்லது கட்டணம் கேட்கப்பட்டது',prize_giveaway:'எதிர்பாராத பரிசு கூறப்படுகிறது',impersonation:'நிறுவனம் அல்லது உறவினர் போல நடிப்பு',suspicious_link:'சந்தேக இணைப்பைத் திறக்க அழுத்தம்',url_shortener:'இணைப்பின் உண்மை இலக்கு மறைக்கப்பட்டது',investment_scam:'நம்ப முடியாத முதலீட்டு லாபம்',delivery_scam:'போலி டெலிவரி செய்தி',act_immediately:'உடனே பதிலளிக்க அழுத்தம்',prize:'எதிர்பாராத பரிசு கூறப்படுகிறது',investment:'நம்ப முடியாத முதலீட்டு வாக்குறுதி',credential:'ரகசிய தகவல் கேட்கப்பட்டது',account:'கணக்கை முடக்கும் மிரட்டல்',gift_card:'கிஃப்ட் கார்டில் பணம் கேட்கப்பட்டது',money_transfer:'பணம் அனுப்பக் கேட்கப்பட்டது',delivery:'போலி டெலிவரி கட்டணம்',tech_support:'போலி தொழில்நுட்ப உதவி',government:'அரசு அமைப்பு போல நடிப்பு',family:'போலி குடும்ப அவசரம்',loan:'கேட்காத கடன் சலுகை',free_reward:'இலவச பரிசு ஆசை',fake_login:'போலி உள்நுழைவு இணைப்பு',raw_ip:'டொமைனுக்கு பதில் IP முகவரி',at_symbol:'இணைப்பில் தவறாக வழிநடத்தும் @',lookalike_domain:'போலி அல்லது ஒத்த டொமைன்',qr_payment:'QR மூலம் பணம் செலுத்தும் ஆபத்து'},
  noSignals:'வலுவான மோசடி அறிகுறி இல்லை; இருப்பினும் கவனமாக இருங்கள்.',actions:['பதிலளிக்காதீர்கள், இணைப்பைத் திறக்காதீர்கள், எந்தக் குறியீடும் பகிராதீர்கள்.','அதிகாரப்பூர்வ செயலி அல்லது எண்ணால் அனுப்புநரை உறுதிசெய்யுங்கள்.','நம்பகமான ஒருவரிடம் இரண்டாவது கருத்து கேளுங்கள்.'],summary:{safe:'வலுவான எச்சரிக்கை இல்லை. எதிர்பாராத கோரிக்கையை தனியாக உறுதிசெய்யுங்கள்.',caution:'இது சந்தேகமாக இருக்கலாம். செயல்படும் முன் அனுப்புநரை உறுதிசெய்யுங்கள்.',high:'வலுவான மோசடி அறிகுறிகள் உள்ளன. பதில், பணம் அல்லது தகவல் கொடுக்காதீர்கள்.'},strongWarning:'பல ஆபத்தான அறிகுறிகள் ஒன்றாக உள்ளன. நிறுத்தி தனியாக உறுதிசெய்யுங்கள்.',disclaimer:'இது ஆபத்து மதிப்பீடு மட்டுமே; உத்தரவாதம் அல்ல.',predictions:{phishing:'ஃபிஷிங்',legitimate:'சரியானது'},
};

const te: LocalizedRiskText = {
  reasons:{urgency:'వెంటనే చర్య తీసుకోవాలనే ఒత్తిడి',account_suspension:'ఖాతాను నిలిపేస్తామని బెదిరింపు',credential_request:'OTP, PIN లేదా పాస్‌వర్డ్ అడిగారు',payment_request:'డబ్బు లేదా రుసుము అడిగారు',prize_giveaway:'అనుకోని బహుమతి দাবি',impersonation:'సంస్థ లేదా పరిచయ వ్యక్తిలా నటించడం',suspicious_link:'సందేహాస్పద లింక్ తెరవమనే ఒత్తిడి',url_shortener:'లింక్ అసలు గమ్యం దాచబడింది',investment_scam:'అవాస్తవ పెట్టుబడి లాభాల హామీ',delivery_scam:'నకిలీ డెలివరీ సందేశం',act_immediately:'ఇప్పుడే స్పందించమనే ఒత్తిడి',prize:'అనుకోని బహుమతి दावा',investment:'అవాస్తవ పెట్టుబడి హామీ',credential:'రహస్య సమాచారం అడిగారు',account:'ఖాతా నిలిపివేత బెదిరింపు',gift_card:'గిఫ్ట్ కార్డుతో చెల్లింపు అడిగారు',money_transfer:'డబ్బు పంపమన్నారు',delivery:'నకిలీ డెలివరీ రుసుము',tech_support:'నకిలీ సాంకేతిక సహాయం',government:'ప్రభుత్వ సంస్థలా నటించడం',family:'నకిలీ కుటుంబ అత్యవసరం',loan:'అడగని రుణ ఆఫర్',free_reward:'ఉచిత బహుమతి ఆశ',fake_login:'నకిలీ లాగిన్ లింక్',raw_ip:'డొమైన్ బదులు IP చిరునామా',at_symbol:'లింక్‌లో తప్పుదారి పట్టించే @',lookalike_domain:'నకిలీ లేదా పోలిన డొమైన్',qr_payment:'QR ద్వారా డబ్బు పంపే ప్రమాదం'},
  noSignals:'బలమైన మోస సంకేతాలు కనిపించలేదు, అయినా జాగ్రత్తగా ఉండండి.',actions:['స్పందించవద్దు, లింక్ తెరవవద్దు, ఎలాంటి కోడ్ పంచుకోవద్దు.','అధికారిక యాప్ లేదా నంబర్ ద్వారా పంపినవారిని ధృవీకరించండి.','నమ్మకమైన వ్యక్తి అభిప్రాయం తీసుకోండి.'],summary:{safe:'బలమైన హెచ్చరిక లేదు. అనుకోని అభ్యర్థనను విడిగా ధృవీకరించండి.',caution:'ఇది సందేహాస్పదంగా ఉండవచ్చు. చర్యకు ముందు పంపినవారిని ధృవీకరించండి.',high:'బలమైన మోస సంకేతాలు ఉన్నాయి. స్పందించవద్దు, చెల్లించవద్దు లేదా సమాచారం ఇవ్వవద్దు.'},strongWarning:'అనేక ప్రమాదకర సంకేతాలు కలిసి ఉన్నాయి. ఆగి విడిగా ధృవీకరించండి.',disclaimer:'ఇది ప్రమాద అంచనా మాత్రమే; హామీ కాదు.',predictions:{phishing:'ఫిషింగ్',legitimate:'చెల్లుబాటు'},
};

const ml: LocalizedRiskText = {
  reasons:{urgency:'ഉടൻ പ്രവർത്തിക്കാനുള്ള സമ്മർദ്ദം',account_suspension:'അക്കൗണ്ട് നിർത്തുമെന്ന ഭീഷണി',credential_request:'OTP, PIN അല്ലെങ്കിൽ പാസ്‌വേഡ് ചോദിച്ചു',payment_request:'പണമോ ഫീസോ ചോദിച്ചു',prize_giveaway:'അപ്രതീക്ഷിത സമ്മാനം അവകാശപ്പെടുന്നു',impersonation:'സ്ഥാപനമായോ പരിചിതനായോ നടിക്കുന്നു',suspicious_link:'സംശയകരമായ ലിങ്ക് തുറക്കാൻ സമ്മർദ്ദം',url_shortener:'ലിങ്കിന്റെ യഥാർത്ഥ ലക്ഷ്യം മറച്ചു',investment_scam:'യാഥാർത്ഥ്യമല്ലാത്ത നിക്ഷേപ ലാഭം',delivery_scam:'വ്യാജ ഡെലിവറി സന്ദേശം',act_immediately:'ഉടൻ മറുപടി നൽകാൻ സമ്മർദ്ദം',prize:'അപ്രതീക്ഷിത സമ്മാന അവകാശവാദം',investment:'യാഥാർത്ഥ്യമല്ലാത്ത നിക്ഷേപ വാഗ്ദാനം',credential:'രഹസ്യ വിവരം ചോദിച്ചു',account:'അക്കൗണ്ട് നിർത്തുമെന്ന ഭീഷണി',gift_card:'ഗിഫ്റ്റ് കാർഡ് വഴി പണം ചോദിച്ചു',money_transfer:'പണം അയയ്ക്കാൻ ആവശ്യപ്പെട്ടു',delivery:'വ്യാജ ഡെലിവറി ഫീസ്',tech_support:'വ്യാജ സാങ്കേതിക സഹായം',government:'സർക്കാർ സ്ഥാപനം പോലെ നടിക്കുന്നു',family:'വ്യാജ കുടുംബ അടിയന്തരാവസ്ഥ',loan:'ആവശ്യപ്പെടാത്ത വായ്പാ വാഗ്ദാനം',free_reward:'സൗജന്യ സമ്മാന പ്രലോഭനം',fake_login:'വ്യാജ ലോഗിൻ ലിങ്ക്',raw_ip:'ഡൊമൈനിന് പകരം IP വിലാസം',at_symbol:'ലിങ്കിൽ തെറ്റിദ്ധരിപ്പിക്കുന്ന @',lookalike_domain:'വ്യാജമോ സമാനമോ ആയ ഡൊമൈൻ',qr_payment:'QR വഴി പണം അയയ്ക്കാനുള്ള അപകടം'},
  noSignals:'ശക്തമായ തട്ടിപ്പ് സൂചനകൾ കണ്ടില്ല; എങ്കിലും ജാഗ്രത പാലിക്കുക.',actions:['മറുപടി നൽകരുത്, ലിങ്ക് തുറക്കരുത്, ഒരു കോഡും പങ്കിടരുത്.','ഔദ്യോഗിക ആപ്പോ നമ്പറോ ഉപയോഗിച്ച് അയച്ചയാളെ സ്ഥിരീകരിക്കുക.','വിശ്വസനീയനായ ഒരാളുടെ അഭിപ്രായം തേടുക.'],summary:{safe:'ശക്തമായ മുന്നറിയിപ്പ് ഇല്ല. അപ്രതീക്ഷിത അഭ്യർത്ഥന സ്വതന്ത്രമായി പരിശോധിക്കുക.',caution:'ഇത് സംശയകരമായിരിക്കാം. പ്രവർത്തിക്കുന്നതിന് മുമ്പ് അയച്ചയാളെ സ്ഥിരീകരിക്കുക.',high:'ശക്തമായ തട്ടിപ്പ് സൂചനകളുണ്ട്. മറുപടി, പണം അല്ലെങ്കിൽ വിവരം നൽകരുത്.'},strongWarning:'ഒന്നിലധികം അപകട സൂചനകൾ ഒരുമിച്ച് കണ്ടെത്തി. നിർത്തി സ്വതന്ത്രമായി പരിശോധിക്കുക.',disclaimer:'ഇത് അപകടത്തിന്റെ ഒരു കണക്ക് മാത്രമാണ്; ഉറപ്പല്ല.',predictions:{phishing:'ഫിഷിംഗ്',legitimate:'നിയമാനുസൃതം'},
};

export const riskText: Record<Language, LocalizedRiskText> = { en, hi, bn, ta, te, ml };
